from settings_base import *

DEBUG = True
PORT = 8888

AWS_ACCESS_KEY = 'xxx'
AWS_SECRET_ACCESS_KEY = 'xxx'

AWS_DYNAMODB_ENDPOINT = 'localhost'
AWS_DYNAMODB_ENDPOINT_PORT = 4567
AWS_DYNAMODB_IS_SECURE = False
AWS_DYNAMODB_VALIDATE_CERT = False
AWS_DYNAMODB_AUTH_REQUESTS = False
